name: Update Mods

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00執行
  workflow_dispatch:     # 允許手動觸發

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install thunderstore-cli from GitHub
        run: |
          echo "Attempting to clone with PAT: *** (hidden for security)"
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/thunderstore-io/thunderstore-cli.git
          cd thunderstore-cli
          pip install .
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Run thunderstore-cli update
        run: |
          # 檢查 thunderstore-cli 的正確命令，根據其文檔調整
          python -m thunderstore_cli update  # 可能需替換為正確的模組名稱或命令
          # 或使用: thunderstore-cli update --help 確認語法

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifest.json
          git commit -m "Auto-update mod versions" || echo "No changes to commit"
          git push