name: Update Mods

on:
  schedule:
    - cron: '0 0 * * *'  # 每天執行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install tsunami from GitHub
        run: |
          git clone https://github.com/ebkr/tsunami.git
          cd tsunami
          pip install .

      - name: Run tsunami update
        run: |
          python -m tsunami update

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifest.json
          git commit -m "Auto-update mod versions" || echo "No changes"
          git push
